// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
	site: 'https://txs.github.io',
	base: '/soft-tennis-guide',
	integrations: [
		starlight({
			title: {
				'zh-TW': '軟式網球入門指南 Intro to Soft Tennis 101',
				en: 'Intro to Soft Tennis 101',
				'zh-CN': '软式网球入门指南 Intro to Soft Tennis 101',
				fr: 'Guide de débutant en Soft Tennis',
				es: 'Guía de inicio en Tenis Suave',
				ru: 'Руководство по началу игры в софт-теннис',
				ms: 'Panduan Soft Tennis untuk Pemula',
				ja: 'ソフトテニス入門ガイド',
				ko: '소프트 테니스 입문 가이드',
			},
			defaultLocale: 'root', // optional
			locales: {
			  root: {
				label: '正體中文',
				lang: 'zh-TW', // lang is required for root locales
			  },
			  'en': {
				label: 'English',
				lang: 'en',
			  },
			  'zh-cn': {
				label: '简体中文',
				lang: 'zh-CN',
			  },
			  'fr': {
				label: 'Français',
				lang: 'fr',
			  },
			  'es': {
				label: 'Español',
				lang: 'es',
			  },
			  'ru': {
				label: 'Русский',
				lang: 'ru',
			  },
			  'ms': {
				label: 'Bahasa Melayu',
				lang: 'ms',
			  },
			  'ja': {
				label: '日本語',
				lang: 'ja',
			  },
			  'ko': {
				label: '한국어',
				lang: 'ko',
			  },
			},
			head:[
				{
					tag: 'script',
					attrs: {
						async: true,
						src: 'https://www.googletagmanager.com/gtag/js?id=G-2VKKN77WMF',
					},
				},
				{
					tag: 'script',
					content: `
						window.dataLayer = window.dataLayer || [];
						function gtag(){dataLayer.push(arguments);}
						gtag('js', new Date());
						gtag('config', 'G-2VKKN77WMF');
					`,
				},
			],
			social: {
				github: 'https://github.com/txs/soft-tennis-guide',
			},
			sidebar: [
				{ 
					label: '前言',
					link: '/preface',
					translations: {
						en: 'Preface',
						'zh-CN': '前言',
						'zh-tw': '前言',
						fr: 'Préface',
						es: 'Prefacio',
						ru: 'Предисловие',
						ms: 'Prakata',
						ja: 'はじめに',
						ko: '소개',
					},
				 },
				{
					label: '軟式網球入門',
					translations: {
						en: 'Introduction to Soft Tennis',
						'zh-CN': '软式网球入门',
						'zh-tw': '軟式網球入門',
						fr: 'Introduction au Soft Tennis',
						es: 'Introducción al Tenis Suave',
						ru: 'Введение в софт-теннис',
						ms: 'Prakata',
						ja: 'ソフトテニス入門',
						ko: '소프트 테니스 입문 가이드',
					},
					items: [
						{ 
							label: '軟網硬網的差異', 
							link: '/introduction/soft-vs-hard-tennis',
							translations: {
								en: 'Differences Between Soft and Hard Tennis',
								'zh-CN': '软网硬网的差异',
								'zh-tw': '軟網硬網的差異',
								fr: 'Différences entre le Soft Tennis et le Tennis Dur',
								es: 'Diferencias entre el Tenis Suave y el Tenis Duro',
								ru: 'Различия между софт-теннисом и хард-теннисом',
								ms: 'Perbezaan antara Tenis Lembut dan Tenis Keras',
								ja: 'ソフトテニスとハードテニスの違い',
								ko: '소프트 테니스와 하드 테니스의 주요 차이점, 라켓, 공, 경기 규칙 등을 알아보세요.',
							},
						},
						{ 
							label: '軟式網球的歷史', 
							link: '/introduction/history-of-soft-tennis',
							translations: {
								en: 'History of Soft Tennis',
								'zh-CN': '软式网球的历史',
								'zh-tw': '軟式網球的歷史',
								fr: 'Histoire du Soft Tennis',
								es: 'Historia del Tenis Suave',
								ru: 'История софт-тенниса',
								ms: 'Sejarah Tenis Lembut',
								ja: 'ソフトテニスの歴史',
								ko: '소프트 테니스의 역사',
							},
						},
						{ 
							label: '軟式網球的魅力', 
							link: '/introduction/charm-of-soft-tennis',
							translations: {
								en: 'The Charm of Soft Tennis',
								'zh-CN': '软式网球的魅力',
								'zh-tw': '軟式網球的魅力',
								fr: 'Le Charme du Soft Tennis',
								es: 'El encanto del Tenis Suave',
								ru: 'Впечатления от софт-тенниса',
								ms: 'Keindahan Tenis Lembut',
								ja: 'ソフトテニスの魅力',
								ko: '소프트 테니스의 매력',
							},
						},
					],
				},
				{
					label: '學習基本規則',
					translations: {
						en: 'Learning Basic Rules',
						'zh-CN': '学习基本规则',
						'zh-tw': '學習基本規則',
						fr: 'Apprendre les règles de base',
						es: 'Aprender las reglas básicas',
						ru: 'Основные правила софт-тенниса',
						ms: 'Pengenalan Peraturan Dasar',
						ja: 'ソフトテニスの基本規則',
						ko: '소프트 테니스의 기본 규칙',
					},
					items: [
						{ 
							label: '軟式網球的基本規則', 
							link: '/basics/rules',
							translations: {
								en: 'Basic Rules of Soft Tennis',
								'zh-CN': '软式网球的基本规则',
								'zh-tw': '軟式網球的基本規則',
								fr: 'Règles de base du Soft Tennis',
								es: 'Reglas básicas del Tenis Suave',
								ru: 'Основные правила софт-тенниса',
								ms: 'Peraturan Dasar Tenis Lembut',
								ja: 'ソフトテニスの基本規則',
								ko: '소프트 테니스의 기본 규칙',
							},
						},
						{ 
							label: '軟式網球的計分方式', 
							link: '/basics/scores',
							translations: {
								en: 'Scoring System of Soft Tennis',
								'zh-CN': '软式网球的计分方式',
								'zh-tw': '軟式網球的計分方式',
								fr: 'Système de notation du Soft Tennis',
								es: 'Sistema de puntuación del Tenis Suave',
								ru: 'Система подсчета очков в софт-теннисе',
								ms: 'Sistem Pemarkahan Tenis Lembut',
								ja: 'ソフトテニスの計分方式',
								ko: '소프트 테니스의 점수 계산 방법',
							},
						},
					],
				},
				{
					label: '第1章：熱身與準備活動',
					translations: {
						en: 'Chapter 1: Warm-up and Preparation Activities',
						'zh-CN': '第1章：热身与准备活动',
						'zh-tw': '第1章：熱身與準備活動',
						fr: 'Chapitre 1 : Préparation et activités de préchauffage',
						es: 'Capítulo 1: Preparación y actividades de calentamiento',
						ru: 'Глава 1: Разминка и подготовительные упражнения',
						ms: 'Bab 1: Persiapan dan Aktiviti Persiapan',
						ja: '第1章：ウォームアップと準備運動',
						ko: '제1장: 준비 운동 및 워밍업 활동',
					},
					items: [
						{ 
							label: '熱身的重要性', 
							link: '/chapter-1/importance-of-warm-up',
							translations: {
								en: 'Importance of Warm-up',
								'zh-CN': '热身的重要性',
								'zh-tw': '熱身的重要性',
								fr: 'Importance du préchauffage',
								es: 'Importancia del calentamiento',
								ru: 'Важность разминки',
								ms: 'Pentingnya Persiapan',
								ja: '熱身の重要性',
								ko: '워밍업의 중요성',
							},
						},
						{ 
							label: '協調性與柔韌性訓練', 
							link: '/chapter-1/coordination-and-flexibility',
							translations: {
								en: 'Coordination and Flexibility Training',
								'zh-CN': '协调性与柔韧性训练',
								'zh-tw': '協調性與柔韌性訓練',
								fr: 'Entraînement de coordination et de souplesse',
								es: 'Entrenamiento de coordinación y flexibilidad',
								ru: 'Упражнения для координации и гибкости',
								ms: 'Latihan untuk Koordinasi dan Kebalikan',
								ko: '협응성 및 유연성 훈련',
							},
						},
						{ 
							label: '基本熱身動作', 
							link: '/chapter-1/basic-warm-up-exercises',
							translations: {
								en: 'Basic Warm-up Exercises',
								'zh-CN': '基本热身动作',
								'zh-tw': '基本熱身動作',
								fr: 'Exercices de préchauffage de base',
								es: 'Ejercicios de calentamiento básicos',
								ru: 'Основные упражнения для разминки',
								ms: 'Latihan Persiapan Dasar',
								ko: '기본 워밍업 운동',
							},
						},
					],
				},
				{
					label: '第2章：基本動作與技巧',
					translations: {
						en: 'Chapter 2: Basic Movements and Techniques',
						'zh-CN': '第2章：基本动作与技巧',
						'zh-tw': '第2章：基本動作與技巧',
						fr: 'Chapitre 2 : Mouvements et techniques de base',
						es: 'Capítulo 2: Movimientos y técnicas básicos',
						ru: 'Глава 2: Основные движения и техники',
						ms: 'Bab 2: Gerakan dan Teknik Dasar',
						ja: '第2章：基本動作とテクニック',
						ko: '제2장: 기본 동작 및 기술',
					},
					items: [
						{ 
							label: '握拍方式', 
							link: '/chapter-2/grip-types',
							translations: {
								en: 'Types of Grips',
								'zh-CN': '握拍方式',
								'zh-tw': '握拍方式',
								fr: 'Types de griffes',
								es: 'Tipos de grifos',
								ru: 'Типы хвата',
								ms: 'Jenis-jenis Gaya Menangkap',
								ja: 'グリップの種類',
								ko: '그립 유형',
							},
						},
						{ 
							label: '基本站姿與步法', 
							link: '/chapter-2/stance-and-footwork',
							translations: {
								en: 'Basic Stance and Footwork',
								'zh-CN': '基本站姿与步法',
								'zh-tw': '基本站姿與步法',
								fr: 'Posture et déplacement de base',
								es: 'Postura y movimientos básicos',
								ru: 'Основные позы и шаги',
								ms: 'Posisi dan Langkah Dasar',
								ja: '基本的な姿勢とフットワーク',
								ko: '기본 자세와 풋워크',
							},
						},
						{ 
							label: '擊球動作', 
							link: '/chapter-2/stroking-techniques',
							translations: {
								en: 'Stroking Techniques',
								'zh-CN': '击球动作',
								'zh-tw': '擊球動作',
								fr: 'Techniques de frappe',
								es: 'Técnicas de golpeo',
								ru: 'Техники удара',
								ms: 'Teknik-teknik Memukul',
								ja: 'ストロークテクニック',
								ko: '스트로크 기술',
							},
						},
					],
				},
				{
					label: '第3章：發球與接發球',
					translations: {
						en: 'Chapter 3: Serving and Receiving',
						'zh-CN': '第3章：发球与接发球',
						'zh-tw': '第3章：發球與接發球',
						fr: 'Chapitre 3 : Service et réception',
						es: 'Capítulo 3: Servir y recibir',
						ru: 'Глава 3: Сервис и прием',
						ms: 'Bab 3: Servis dan Menerima',
						ja: '第3章：サーブとレシーブ',
						ko: '제3장: 서브 및 리시브',
					},
					items: [
						{ 
							label: '發球技巧', 
							link: '/chapter-3/serving-techniques',
							translations: {
								en: 'Serving Techniques',
								'zh-CN': '发球技巧',
								'zh-tw': '發球技巧',
								fr: 'Techniques de service',
								es: 'Técnicas de servicio',
								ru: 'Техники подачи',
								ms: 'Teknik Servis',
								ja: 'サービングテクニック',
								ko: '서브 및 리시브',
							},
						},
						{ 
							label: '接發球要點', 
							link: '/chapter-3/receiving-strategies',
							translations: {
								en: 'Receiving Strategies',
								'zh-CN': '接发球要点',
								'zh-tw': '接發球要點',
								fr: 'Stratégies de réception',
								es: 'Técnicas de recepción',
								ru: 'Техники приема',
								ms: 'Teknik Menerima',
								ja: 'レシービング戦略',
								ko: '리시브 전략',
							},
						},
					],
				},
				{
					label: '第4章：網前截擊與防守',
					translations: {
						en: 'Chapter 4: Volleying and Defending',
						'zh-CN': '第4章：网前截击与防守',
						'zh-tw': '第4章：網前截擊與防守',
						fr: 'Chapitre 4 : Volée et défense',
						es: 'Capítulo 4: Volteo y defensa',
						ru: 'Глава 4: Высокие удары и защита',
						ms: 'Bab 4: Voli dan Pertahanan',
						ja: '第4章：ボレーと守備',
						ko: '제4장: 네트 위 버리 및 방어',
					},
					items: [
						{ 
							label: '截擊技巧', 
							link: '/chapter-4/volley-techniques',
							translations: {
								en: 'Volley Techniques',
								'zh-CN': '截击技巧',
								'zh-tw': '截擊技巧',
								fr: 'Techniques de volée',
								es: 'Técnicas de volteo',
								ru: 'Техники высоких ударов',
								ms: 'Teknik Voli',
								ja: 'ボレーテクニック',
								ko: '네트 위 버리 및 방어',
							},
						},
						{ 
							label: '防守策略', 
							link: '/chapter-4/defensive-strategies',
							translations: {
								en: 'Defensive Strategies',
								'zh-CN': '防守策略',
								'zh-tw': '防守策略',
								fr: 'Stratégies de défense',
								es: 'Técnicas de defensa',
								ru: 'Техники защиты',
								ms: 'Teknik Pertahanan',
								ja: '守備戦略',
								ko: '방어 전략',
							},
						},
					],
				},
				{
					label: '第5章：進階技巧與戰術',
					translations: {
						en: 'Chapter 5: Advanced Skills and Tactics',
						'zh-CN': '第5章：进阶技巧与战术',
						'zh-tw': '第5章：進階技巧與戰術',
						fr: 'Chapitre 5 : Compétences avancées et tactiques',
						es: 'Capítulo 5: Técnicas avanzadas y estrategias',
						ru: 'Глава 5: Улучшенные навыки и стратегии',
						ms: 'Bab 5: Kemahiran Lanjutan dan Taktik',
						ja: '第5章：高度なスキルと戦術',
						ko: '제5장: 고급 기술 및 전략',
					},
					items: [
						{ 
							label: '進階技巧', 
							link: '/chapter-5/advanced-skills',
							translations: {
								en: 'Advanced Skills',
								'zh-CN': '进阶技巧',
								'zh-tw': '進階技巧',
								fr: 'Compétences avancées',
								es: 'Técnicas avanzadas',
								ru: 'Улучшенные навыки',
								ms: 'Kemahiran Lanjutan',
								ja: '高度なスキル',
								ko: '고급 기술',
							},
						},
						{ 
							label: '戰術運用', 
							link: '/chapter-5/tactical-applications',
							translations: {
								en: 'Tactical Applications',
								'zh-CN': '战术运用',
								'zh-tw': '戰術運用',
								fr: 'Applications tactiques',
								es: 'Aplicación de estrategias',
								ru: 'Применение стратегий',
								ms: 'Aplikasi Taktikal',
								ja: '戦術の応用',
								ko: '고급 전략',
							},
						},
					],
				},
				{
					label: '第6章：單打與雙打比賽',
					translations: {
						en: 'Chapter 6: Singles and Doubles Matches',
						'zh-CN': '第6章：单打与双打比赛',
						'zh-tw': '第6章：單打與雙打比賽',
						fr: 'Chapitre 6 : Jeux simples et doubles',
						es: 'Capítulo 6: Partidos de simple y dobles',
						ru: 'Глава 6: Одиночные и двойные матчи',
						ms: 'Bab 6: Permainan Satu dan Dua',
						ja: '第6章：シングルスとダブルスの試合',
						ko: '제6장: 단식과 복식 경기',
					},
					items: [
						{ 
							label: '單打技術', 
							link: '/chapter-6/singles-techniques',
							translations: {
								en: 'Singles Techniques',
								'zh-CN': '单打技术',
								'zh-tw': '單打技術',
								fr: 'Techniques de simple',
								es: 'Técnicas de simple',
								ru: 'Техники одиночных',
								ms: 'Teknik Satu',
								ja: 'シングルスのテクニック',
								ko: '단식 기술',
							},
						},
						{ 
							label: '雙打配合', 
							link: '/chapter-6/doubles-coordination',
							translations: {
								en: 'Doubles Coordination',
								'zh-CN': '双打配合',
								'zh-tw': '雙打配合',
								fr: 'Coordination de double',
								es: 'Coordinación de dobles',
								ru: 'Техники двойных',
								ms: 'Koordinasi Dua',
								ja: 'ダブルスの連携',
								ko: '복식 협력',
							},
						},
					],
				},
				{
					label: '第7章：訓練與比賽準備',
					translations: {
						en: 'Chapter 7: Training and Match Preparation',
						'zh-CN': '第7章：训练与比赛准备',
						'zh-tw': '第7章：訓練與比賽準備',
						fr: 'Chapitre 7 : Entraînement et préparation de match',
						es: 'Capítulo 7: Entrenamiento y preparación de partidos',
						ru: 'Глава 7: Обучение и подготовка к матчам',
						ms: 'Bab 7: Latihan dan Persiapan Permainan',
						ja: '第7章：トレーニングと試合準',
						ko: '제7장: 훈련과 경기 준비',
					},
					items: [
						{ 
							label: '綜合技能訓練', 
							link: '/chapter-7/comprehensive-skill-training',
							translations: {
								en: 'Comprehensive Skill Training',
								'zh-CN': '综合技能训练',
								'zh-tw': '綜合技能訓練',
								fr: 'Entraînement de compétences complètes',
								es: 'Entrenamiento de habilidades completas',
								ru: 'Обучение и подготовка к матчам',
								ms: 'Latihan Komprehensif',
								ja: '総合的なスキルトレーニング',
								ko: '종합 기술 훈련',
							},
						},
						{ 
							label: '比賽心態與準備', 
							link: '/chapter-7/match-preparation',
							translations: {
								en: 'Match Mindset and Preparation',
								'zh-CN': '比赛心态与准备',
								'zh-tw': '比賽心態與準備',
								fr: 'Mentalité de match et préparation',
								es: 'Mentalidad de partido y preparación',
								ru: 'Ментальность матча и подготовка',
								ms: 'Persiapan Permainan dan Mentalitas',
								ja: '試合のメンタリティと準備',
								ko: '경기 마인드셋과 준비',
							},
						},
					],
				},
				{
					label: '結論',
					translations: {
						en: 'Conclusion',
						'zh-CN': '结论',
						'zh-tw': '結論',
						fr: 'Conclusion',
						es: 'Conclusión',
						ru: 'Заключение',
						ms: 'Kesimpulan',
						ja: '結論',
						ko: '결론',
					},
					items: [
						{ 
							label: '軟式網球的魅力與挑戰', 
							link: '/conclusion/soft-tennis-charm',
							translations: {
								en: 'The Charm and Challenges of Soft Tennis',
								'zh-CN': '软式网球的魅力与挑战',
								'zh-tw': '軟式網球的魅力與挑戰',
								fr: 'Charme et défis du Soft Tennis',
								es: 'Encanto y desafíos del Tenis Suave',
								ru: 'Очарование и трудности софт-тенниса',
								ms: 'Keindahan dan Masalah Tenis Lembut',
								ja: 'ソフトテニスの魅力と課題',
								ko: '소프트 테니스의 매력과 도전',
							},
						},
						{ 
							label: '未來的網球之路', 
							link: '/conclusion/future-tennis-path',
							translations: {
								en: 'The Future of Tennis Path',
								'zh-CN': '未来的网球之路',
								'zh-tw': '未來的網球之路',
								fr: 'Le futur du tennis',
								es: 'El futuro del tenis',
								ru: 'Будущее пути в теннис',
								ms: 'Jalan Masa Depan Tenis Lembut',
								ja: '未来のテニスの道',
								ko: '테니스의 미래 방향',
							},
						},
					],
				},
				{
					label: '附錄',
					translations: {
						en: 'Appendix',
						'zh-CN': '附录',
						'zh-tw': '附錄',
						fr: 'Appendice',
						es: 'Apéndice',
						ru: 'Приложение',
						ms: 'Lampiran',
						ja: '付録',
						ko: '부록',
					},
					items: [
						{ 
							label: '常見問題解答', 
							link: '/appendix/faq',
							translations: {
								en: 'Frequently Asked Questions',
								'zh-CN': '常见问题解答',
								'zh-tw': '常見問題解答',
								fr: 'Questions fréquemment posées',
								es: 'Preguntas frecuentes',
								ru: 'Часто задаваемые вопросы',
								ms: 'Soalan yang Sering Diajukan',
								ja: 'よくある質問',
								ko: '자주 묻는 질문',
							},
						},
						{ 
							label: '推薦資源', 
							link: '/appendix/recommended-resources',
							translations: {
								en: 'Recommended Resources',
								'zh-CN': '推荐资源',
								'zh-tw': '推薦資源',
								fr: 'Ressources recommandées',
								es: 'Recursos recomendados',
								ru: 'Рекомендуемые ресурсы',
								ms: 'Sumber yang Disyorkan',
								ja: '推薦資源',
								ko: '추천 자료',
							},
						},
					],
				},
			],
			customCss: [
				'./src/styles/soft-tennis.css',
			],
			components: {
				Footer: './src/components/Footer.astro',
				PageSidebar: './src/components/PageSidebar.astro',
			},
			// ... (rest of the configuration)
		}),
	],
});